# Generated by Django 5.2.8 on 2025-11-21 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_trainingday_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_excused',
            field=models.BooleanField(default=False, verbose_name='إثبات الغياب (بعذر)'),
        ),
        migrations.AddField(
            model_name='company',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='المشرف بالمؤسسة'),
        ),
        migrations.AddField(
            model_name='company',
            name='training_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع التدريب'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='behavior',
            field=models.IntegerField(default=0, verbose_name='السلوك'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='learning_level',
            field=models.IntegerField(default=0, verbose_name='مستوى التعلم'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='performance_quality',
            field=models.IntegerField(default=0, verbose_name='جودة الأداء'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='practical_skills',
            field=models.IntegerField(default=0, verbose_name='المهارات العملية'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='punctuality',
            field=models.IntegerField(default=0, verbose_name='الالتزام بالمواعيد'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='teamwork',
            field=models.IntegerField(default=0, verbose_name='العمل ضمن فريق'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('suspended', 'متوقف'), ('graduated', 'خريج')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'مدير فرع'), ('supervisor', 'مشرف'), ('employee', 'موظف'), ('institution', 'مؤسسة تدريبية')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سبب الغياب'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='البلاغات والملاحظات'),
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'إضافة'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('LOGIN', 'تسجيل دخول'), ('LOGIN_FAILED', 'فشل دخول')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
