# Generated by Django 5.2.8 on 2025-11-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='attendance_proofs/', verbose_name='ملف إثبات العذر'),
        ),
        migrations.AddField(
            model_name='student',
            name='personal_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students_photos/', verbose_name='صورة الطالب'),
        ),
    ]
